name: proklinik_staff_portal
description: "ProKliniK staff portal for administrative management."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter    


  cupertino_icons: ^1.0.6
  proklinik_models:
    git:
      url: https://github.com/pheonixeye/proklinik_models.git
      ref: master
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.19.0
  pocketbase: ^0.18.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  go_router: ^14.3.0
  equatable: ^2.0.5
  after_layout: ^1.2.0
  email_validator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/